"""Change description field to body

Revision ID: 7d61bf53d079
Revises: 1d2a3aaf3e68
Create Date: 2026-07-17 14:16:59.009374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d61bf53d079'
down_revision: Union[str, Sequence[str], None] = '1d2a3aaf3e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('events', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('events', 'body')
    # ### end Alembic commands ###
