"""Make other_names field optional

Revision ID: b7d49de2f7da
Revises: 7d61bf53d079
Create Date: 2026-07-20 12:15:26.143425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'b7d49de2f7da'
down_revision: Union[str, Sequence[str], None] = '7d61bf53d079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'other_names',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'other_names',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
