"""Create db and tables

Revision ID: 6762ef53f645
Revises: 
Create Date: 2026-07-08 18:15:31.659222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6762ef53f645'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('program', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('other_names', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_subscribers_name'), 'subscribers', ['name'], unique=False)
    op.create_index(op.f('ix_subscribers_other_names'), 'subscribers', ['other_names'], unique=False)
    op.create_index(op.f('ix_subscribers_surname'), 'subscribers', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_surname'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_other_names'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_name'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
